### ISSUE TITLE
getAccessTokenAsync returns error 13007

### ISSUE THREAD

**Issue by kbrothers98** [OfficeDev/Office-Add-in-ASPNET-SSO#5] opened 2017-07-24 15:31 UTC
When I click "Get My Files from OneDrive" I get an error, see screenshot below.
![image](https://user-images.githubusercontent.com/3487178/28530542-6cb98608-7051-11e7-8e06-0f642560c461.png)

My office version is 1705 (Build 8201.2136 Click-to-Run).
My visual studio version is Visual Studio Community 2017 Preview (2) Version 15.3.0 Preview 4.0 

This issue many be the same as issue #4. However I was not able to resolve it by following the instructions provided for that issue.  

I am using the latest sample code.
I registered and consented the app with the same azure admin's credentials. 
I am using my own (non-admin) credentials with PowerPoint. 

Thank you.

**Comment by Rick-Kirkham** [comment] 2017-07-24 17:44
@anonybros 
I'm not able to reproduce. 
I'm not sure what you mean by "azure admin's credentials". The admin of an Azure tenancy is usually a Microsoft Account ID. The preview of SSO does not support MSA IDs. You need to use an Office 365 account, which I think is always a *.onmicrosoft.com ID. It should be the admin of the Office 365 tenancy. 
Be sure the user that you log into PowerPoint with is a user in the same Office 365 tenancy.
Also, if the above is not the problem, be sure you are logged in to PowerPoint with only one identity. It should be a user in the Office 365 tenancy. 
If none of the above are the problem, try logging in to PowerPoint with the **same Office 365 admin** credentials that you use to register/consent the add-in. That shouldn't be necessary, but it might be informative if it works. 
If none of the above is the problem. You might try turning on Fiddler just before you press the "Get My Files from OneDrive" button. See if the call from Office to the V2 endpoint is captured.

**Comment by kbrothers98** [comment] 2017-07-26 22:20
@Rick-Kirkham 
Thank you for the quick response. 
I was able to get past the 13007 temporarily by making myself an Office365 admin. I ran through the registration process again. At which point  I got a 13003 error using that admin account. That prompted me to use another normal account to sign into power point. Once I did that I got a 17007 regardless of who I signed in as.
Could you please explain to me (or link to the correct documentation) what types of accounts there are?

**Comment by Rick-Kirkham** [comment] 2017-07-27 01:11
I can't find an error numbered 17007 in the code. Did you mean 13007? 

13003 means that you are not logged into PowerPoint with an Office 365 ID. You must be logged in with a Microsoft Account, which is not supported in the preview. (Another possibility is that you are logged into PowerPoint with more than one ID and one of them is a Microsoft Account.)  

If I Bing "what's the difference between Microsoft Account and Office 365 account?" I get hits. Basically, Microsoft Account has been around since the late 1990s (although it wasn't always called "Microsoft Account"). It is a free account available to individuals that is parallel to a Yahoo or Google account. Depending on what era you signed up, your email will end with msn.com, live.com, hotmail.com, or outlook.com. Office 365 is a set of online services that are not for free (except for the free developer tenancy that you can get -- see below). A tenancy to Office 365 is usually purchased by businesses/schools and an individual's workplace or school assigns him/her an ID so they can login to the tenancy. Email is one of the services and an Office 365 email ID has the form `username@{some-domain}.onmicrosoft.com`. 

If you don't already have a developer Office 365 tenancy, I recommend you get one and use it for development. Go to [Set up a development environment for SharePoint Add ins on Office 365](https://dev.office.com/sharepoint/docs/sp-add-ins/set-up-a-development-environment-for-sharepoint-add-ins-on-office-365) and scroll down to the section **Sign up for an Office 365 Developer Site**. Don't worry about "SharePoint" in the title. What you'll be getting is an Office 365 tenancy and you will automatically be the admin of it. Once you've got it up and running, use the {some-domain}.onmicrosoft.com ID that was created for you as part of the process in all of the steps in the article that the readme of this repo links to.

**Comment by manufz** [comment] 2017-07-27 09:08
I get the same error (13007) as @anonybros.
My Office and VS version is also the same.
-Office 1705 (Build 8201.2136 Click-to-Run)).
-VS 2017 Professional Version 15.3.0 Preview 4.0

I successfully consented to the app with an admin account. In the Office application I am signed in with a standard Office 365 account from the same tenant.

This is what Fiddler records after pressing the button "Get My Files from OneDrive":
![fiddler1](https://user-images.githubusercontent.com/30493494/28662766-9864e768-72bb-11e7-8484-d1471d6ebb76.jpg)

**Comment by Rick-Kirkham** [comment] 2017-07-27 18:14
@apollon7 
Before I escalate this to the product team, let me ask: Are you really, really, really, really sure that you are logged into PowerPoint with just one ID and it is an Office 365 ID (which would normally have the form name@somedomain.onmicrosoft.com? To check, open PowerPoint and start a new presentation. Click your name on the right of the title bar. Click **Switch account**. On the **Accounts** window that opens, there should be just a single account listed, the Office 365 account.

**Comment by manufz** [comment] 2017-07-28 05:44
@Rick-Kirkham Thanks for the quick response.
Yes, I am logged in with only one account and yes it is an account from our Office 365 tenant. Because we have domain specific email addresses it is not ending with "somedomain.onmicrosoft.com" but I think that was just a hint so.

**Comment by Rick-Kirkham** [comment] 2017-07-28 16:32
@apollon7 
Please use the Fiddler inspector to open the first Request to **login.windows.net/common/oauth2/token**. The body should look something like this:

**grant_type=refresh_token
&refresh_token={LONG-TOKEN-OMITTED}
&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob
&client_id=d3590ed6-52b3-4102-aeff-aad2292ab01c
&resource=https%3a%2f%2fofficeapps.live.com**

Does yours look different in any way? In particular, do you have the same **resource** value?
Also, does the second Request to **login.windows.net/common/oauth2/token** differ from the first?

**Comment by manufz** [comment] 2017-07-31 09:59
No, the resource parameter in my case contains the Application ID URI.
The two requests to **login.windows.net/common/oauth2/token** have the same body.

**Comment by Rick-Kirkham** [comment] 2017-07-31 15:14
@apollon7 
Someone internally had the same symptoms. I've asked the product team for help. I'll report back here what I learn.

**Comment by TimMcMSFT** [comment] 2017-08-04 20:37
Hi @apollon7, thanks for working through this with us. I want to step through some basics here. We've seen these issues before, but they're almost always due to the burdensome configuration steps needed for SSO.

1) The sample used to have the service and manifest request "profile" permissions. If you still see this as part of the request in either place, please clean it up. You'll just want User.Read.
2) Unfortunately we still need to use admin consent. For this step, the Tenant Admin must make the consent with the appropriate permissions (see #1)
3) The user in Office must be a user from the Tenant in #2. Sometimes Office keeps other users lingering in the cache (if you've just switched), so it's best to make sure that you've totally closed down all Office apps after you switch the account. Then try to call the API again.

For more rigorous verification, you could share the manifest snippet, Azure Registration Permissions listed, the relevant user accounts used, and the Url to the Admin Consent endpoint that you used to grant Consent. That would confirm any config/protocol inconsistencies.

Thanks, -Tim

**Comment by Rick-Kirkham** [comment] 2017-08-05 01:11
Regarding Tim's #1, I think it's actually Files.Read.All that you want, not User.Read

**Comment by manufz** [comment] 2017-08-07 07:24
Hello @TimMcMSFT , thanks for your response.
1. Yes, I have the new version (920957d) with the right permissions set.
2. An admin consented to the permissions. The link I used was: https://login.microsoftonline.com/common/adminconsent?client_id={myclientid}&state=12345 (with the client id replaced). After consenting the redirect url contained "adminconsent=true" without any errors.
3. I always work with the same tenant so there can't be no mix up.

I tried it with the code under "Before" but also "Complete" so there should be no mistakes there.

The applications manifest looks as follows:
![app_manifest](https://user-images.githubusercontent.com/30493494/29014798-3f046c50-7b4b-11e7-84d0-ff3dd98fe385.jpg)

A snippet of the manifest of my Add-In:
![add-in_manifest](https://user-images.githubusercontent.com/30493494/29014615-3a2681d8-7b4a-11e7-83cc-5254171d591c.jpg)
`
And the appSettings in Web.config:
![appsettings](https://user-images.githubusercontent.com/30493494/29014983-342cb570-7b4c-11e7-8ffa-b49f91f29766.png)

I hope it helps somehow.

**Comment by Rick-Kirkham** [comment] 2017-08-08 17:41
@apollon7 
The only difference I can see between your configuration and mine (which is working) is that the tags value at the end of my registration manifest is just empty square brackets: []. I notice that you have five tags. One of them sets the token version to "1". The tokens that I get have version 2. Could you try changing your "1" to "2" and see if that fixes things? If that doesn't work, try removing all the tags, so the line reads `"tags": []` and then test. If it works, then add back the tags one-by-one and test between each addition to see which one breaks it. 
Also, regarding Tim's number 3 above, he's really making two points: 
3.a. The user in Office must be a user from the Tenant in # 2. 
3.b. Sometimes Office keeps other users lingering in the cache (if you've just switched from one user to another), so it's best to make sure that you've _**totally closed down all Office apps**_ after you switch the account. Then try to call the API again.

**Comment by manufz** [comment] 2017-08-09 13:21
@Rick-Kirkham 
Unfortunately it made no difference clearing "tags" or modifying the values in it.
Regarding 3.b.: I am only working with one account in Office so that shouldn't be a problem. I still tried logging out and in again but also had no success.

**Comment by Rick-Kirkham** [comment] 2017-08-09 16:44
Please provide the raw HTTP Request from Fiddler when you get 400 from the endpoint `login.windows.net/common/oauth2/token`

**Comment by manufz** [comment] 2017-08-10 05:46
Okay below you can see the two requests to `login.windows.net/common/oauth2/token`.
The only differences between them are the  `client-request-id` and the additional "Cookie" in the second request.

First request:
```
POST https://login.windows.net/common/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
client-request-id: 31...
return-client-request-id: false
x-client-OS: 10.0.14393
x-client-SKU: Win32
x-client-Ver: v1.0.2063.20170117
x-ms-PKeyAuth: 1.0
Host: login.windows.net
Content-Length: 1080
Cache-Control: no-cache

grant_type=refresh_token&refresh_token=AQABA...&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=d35...&resource=api://localhost:44355/{my Application ID}
```


Second request:
```
POST https://login.windows.net/common/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
client-request-id: 13...
return-client-request-id: false
x-client-OS: 10.0.14393
x-client-SKU: Win32
x-client-Ver: v1.0.2063.20170117
x-ms-PKeyAuth: 1.0
Host: login.windows.net
Content-Length: 1080
Cache-Control: no-cache
Cookie: x-ms-gateway-slice=002; stsservicecookie=ests

grant_type=refresh_token&refresh_token=AQABA...&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=d35...&resource=api://localhost:44355/{my Application ID}
```

PS: I just saw that in the first screenshot of Fiddler you can see `localhost:44356`. That's just because I tried the "Before" and "Complete" sample and missed to check the port number the second time. Yes, I am using the same port for everything (`44355`).

**Comment by Rick-Kirkham** [comment] 2017-08-10 19:30
I'm sorry, I should have asked for the raw Response too, so we can see what the specific error underlying the 400 is. 

And one more experiment. Try changing `forceConsent `to `true `in the call to `getAccessTokenAsync`.

**Comment by manufz** [comment] 2017-08-11 04:40
Okay I see, the error from the response is as follows:
`"error":"invalid_scope","error_description":"AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope profile is not valid.`

(Changing `forceConsent `to `true `doesn't change anything.)

**Comment by Rick-Kirkham** [comment] 2017-08-11 06:37
@apollon7 
In the file values.controller.cs you should see the following line:
`string[] graphScopes = { "Files.Read.All" };`
Does it look like this in your project, or is "profiles" included in the array? If "profiles" is included, then you don't have the latest version of the sample.

**Comment by manufz** [comment] 2017-08-11 06:46
No, it is `string[] graphScopes = { "Files.Read.All" };`.

**Comment by Rick-Kirkham** [comment] 2017-08-11 16:30
OK. @TimMcMSFT  tells me that the error that you are seeing in Fiddler means that something has gone wrong with the admin consent. We recommend that you go through that process again. Be sure you are logged in as an admin of the O365 tenancy. You should be prompted to consent to (at least) the 3 MS Graph scopes that you asked for in the app registration (and in the manifest). I recommend that you press F5 in VS so that the app is up and running before you do the admin consent. If the consent succeeds, the browser window will be redirected to the add-ins home page.

**Comment by manufz** [comment] 2017-08-14 08:10
I tried the consent once more but there does not seem to be a problem with it. When I call the (further above mentioned) url I login with an global admin account from my tenant. After that I see the permissions listed for which I need a consent. After confirming them I get a successful response ("admin_consent=true" and my tenant id). So no indication that anything has gone wrong.

**Comment by Rick-Kirkham** [comment] 2017-08-14 18:15
Please upgrade your Office Click-to-Run to a version at least 170**7**. Then try again.

**Comment by LeanderVanEck** [comment] 2017-08-16 09:00
I'm having similar issues in Word with Office Click-to-Run version 1705. (I have all the latest updates installed). What i found is that the user first needs to consent to the application. Only after user consent (or admin consent) is granted then SSO performs as i would expect.

I'm not sure what the `forceConsent` is supposed to do, but i doesn't seem to make any difference.

Is this behavior by design? I expected Office to display the user consent page if so needed.

**Comment by Rick-Kirkham** [comment] 2017-08-16 15:31
Admin consent is only needed during development. The article which the readme points to explains how to do it.

**Comment by Rick-Kirkham** [comment] 2017-08-31 21:19
Passing on a discovery to everyone who is using the "Complete" version of the sample. There was a typo in one of the .csproj files. The IIS server port was set to 44356 when it should be 44355. I don't know if that is causing the 13007, but you should fix it in your copy at any rate. I've done so in the source, but if you don't want to download it again, You can open https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO/blob/master/Complete/Office-Add-in-ASPNET-SSO-WebAPI/Office-Add-in-ASPNET-SSO-WebAPI.csproj. in a text editor (With Visual Studio closed.) Search for the 44356 and change it to 44355. Save the file and then you can reopen the project in VS. 
**UPDATE**: A Office-Add-in-ASPNET-SSO-WebAPI.csproj.user file which is not in the repo itself gets created when you first open the project and the erroneous port number gets inserted into it, so you have to fix this .csproj.user file as well.

**Comment by prashantharshi** [comment] 2017-09-05 09:59
Even i am facing the same issue , version : 1707 and build 8326.2096
Fiddler trace shows 400 and 302 status code as indicated above for api calls

**Comment by Rick-Kirkham** [comment] 2017-09-05 17:03
@apollon7 and @prashantharshi  are both reporting that this is fixed by adding (1) `profile `to the Microsoft Graph Permissions when you register the add-in, and (2) repeating the admin consent process. I can reproduce that 13007 comes and goes depending on whether `profile `permission has been granted (assuming no other known cause of 13007 applies). 
Note, BTW, there is no way to selectively revoke a permission to Microsoft Graph at this time. If you want to reduce the permissions that an app has, you have to register it and ask for the smaller set of permissions. (Then, optionally, delete the old registration.)

**Closed as completed by Rick-Kirkham** 2017-09-05 17:03 UTC
