### ISSUE TITLE
call api/values and recive error code 401 

### ISSUE THREAD

**Issue by hq1993922** [OfficeDev/Office-Add-in-ASPNET-SSO#32] opened 2019-04-18 07:04 UTC
same as  #9.
here is the snapshot in fiddler.
![image](https://user-images.githubusercontent.com/23725260/56336932-12a14d00-61d5-11e9-9d3b-40c0c46d8e3e.png)

ClientID, Audience , Password and Issuer has been set
![image](https://user-images.githubusercontent.com/23725260/56337259-ef779d00-61d6-11e9-86bd-799a4c26357a.png)

when getData has called, server-side returns error code 401 {"Message":"Authorization has been denied for this request."}

It blocked in auth middleware.

**Comment by Rick-Kirkham** [comment] 2019-04-18 14:11
Please use the Visual Studio debugger to find the point in the server side code where the process fails.

**Comment by hq1993922** [comment] 2019-04-19 04:02
It cannot hit the breakpoint in /api/values. Seems like the error was thrown by 
 middleware  `OAuthBearerAuthentication`
![image](https://user-images.githubusercontent.com/23725260/56403442-eb5d8500-6293-11e9-9f66-0c4149af377e.png)

**Comment by Rick-Kirkham** [comment] 2019-04-19 05:19
OK. I can't reproduce. Can you put some breakpoints in that OWIN-related files and narrow down where the problem is?

**Comment by hq1993922** [comment] 2019-04-19 08:18
I run the complete solution. Configuration has been listed the of the project and leave others unchanged.

Startup.Auth.cs snapshot
![image](https://user-images.githubusercontent.com/23725260/56414832-6a67b300-62be-11e9-8e33-ac28c4d200f2.png)

![image](https://user-images.githubusercontent.com/23725260/56414293-bb76a780-62bc-11e9-9e7c-66256dd762cb.png)

web.config
  ```
    <add key="ida:Tenant" value="https://login.microsoftonline.com/common/v2.0" />
    <add key="ida:ClientID" value="b33256e8-65ff-4668-b6a5-98ad831feb4b" />
    <add key="ida:Audience" value="b33256e8-65ff-4668-b6a5-98ad831feb4b" />
    <add key="ida:Password" value="YtqG7BYf12buK?1iC-ts+V?wY*Eh27pK" />
    <add key="ida:Issuer" value="https://login.microsoftonline.com/5ae7bf6a-a3e7-4888-9c63-4f698caef37d/v2.0" />
```
AddIn configuration
 ```
<WebApplicationInfo>
      <Id>b33256e8-65ff-4668-b6a5-98ad831feb4b</Id>
      <Resource>api://localhost:44355/b33256e8-65ff-4668-b6a5-98ad831feb4b</Resource>
      <Scopes>
        <Scope>openid</Scope>
        <Scope>offline_access</Scope>
        <Scope>profile</Scope>
        <Scope>files.read.all</Scope>
      </Scopes>
    </WebApplicationInfo>
```
Manifest of Azure App
```
{
	"id": "9c7e8039-362e-40c5-a531-305a90ebb934",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "b33256e8-65ff-4668-b6a5-98ad831feb4b",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2019-04-18T04:52:50Z",
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://localhost:44355/b33256e8-65ff-4668-b6a5-98ad831feb4b"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "sso auth",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "Enable Office to call the add-in's web APIs with the same rights as the current user.",
			"adminConsentDisplayName": "Office can act as the user.",
			"id": "7f577b41-cd37-4c60-bf76-2914a5d27424",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": "Enable Office to call the add-in's web APIs with the same rights that you have.",
			"userConsentDisplayName": "Office can act as you.",
			"value": "access_as_user"
		},
		{
			"adminConsentDescription": "offline_access",
			"adminConsentDisplayName": "offline_access",
			"id": "0693724b-5d1c-4665-9639-762056810955",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": null,
			"userConsentDisplayName": null,
			"value": "offline_access"
		},
		{
			"adminConsentDescription": "file.read",
			"adminConsentDisplayName": "file.read",
			"id": "87d6cc6c-d14b-4977-8ecf-f3b6111a9316",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": null,
			"userConsentDisplayName": null,
			"value": "file.read"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2020-04-18T07:41:21.947Z",
			"keyId": "8c9eb5fb-814e-4137-af7c-e59d342d1f53",
			"startDate": "2019-04-18T07:41:29.11Z",
			"value": null,
			"createdOn": "2019-04-18T07:41:34.3439208Z",
			"hint": "Ytq",
			"displayName": "Password uploaded on Thu Apr 18 2019"
		}
	],
	"preAuthorizedApplications": [
		{
			"appId": "bc59ab01-8403-45c6-8796-ac3ef710b3e3",
			"permissionIds": [
				"7f577b41-cd37-4c60-bf76-2914a5d27424",
				"87d6cc6c-d14b-4977-8ecf-f3b6111a9316",
				"0693724b-5d1c-4665-9639-762056810955"
			]
		},
		{
			"appId": "57fb890c-0dab-4253-a5e0-7188c88b2bb4",
			"permissionIds": [
				"7f577b41-cd37-4c60-bf76-2914a5d27424"
			]
		},
		{
			"appId": "d3590ed6-52b3-4102-aeff-aad2292ab01c",
			"permissionIds": [
				"7f577b41-cd37-4c60-bf76-2914a5d27424"
			]
		}
	],
	"publisherDomain": "hq1993922163.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "https://localhost:44355",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
					"type": "Scope"
				},
				{
					"id": "37f7f235-527c-4136-accd-4a02d197296e",
					"type": "Scope"
				},
				{
					"id": "14dad69e-099b-42c9-810b-d002981feec1",
					"type": "Scope"
				},
				{
					"id": "df85f4d6-205c-4ac5-a5ea-6bf408dba283",
					"type": "Scope"
				},
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADMultipleOrgs",
	"tags": [],
	"tokenEncryptionKeyId": null
}
```

**Comment by Rick-Kirkham** [comment] 2019-04-19 23:52
I see several problems in the Azure manifest, so I recommend that you delete the registration and redo the procedure described here [register-the-add-in-with-azure-ad-v20-endpoint](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet#register-the-add-in-with-azure-ad-v20-endpoint).

Here are the problems in your current manifest:

The `oauth2Permissions` array should have only 1 object, for `access_as_user`. Like this:

```
	"oauth2Permissions": [
		{
			"adminConsentDescription": "Allow the client application to access Office-Add-in-ASPNET-SSO3 on behalf of the signed-in user.",
			"adminConsentDisplayName": "Access Office-Add-in-ASPNET-SSO3",
			"id": "ecc79359-1c3b-4867-8d41-dac3aa1af9b5",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": "Allow the client application to access Office-Add-in-ASPNET-SSO3 on your behalf.",
			"userConsentDisplayName": "Access Office-Add-in-ASPNET-SSO3",
			"value": "access_as_user"
		}
	],
```
The `preAuthorizedApplications` array should have only 1 `permissionIds` for each `appId`. Like this:

```
"preAuthorizedApplications": [
		{
			"appId": "bc59ab01-8403-45c6-8796-ac3ef710b3e3",
			"permissionIds": [
				"ecc79359-1c3b-4867-8d41-dac3aa1af9b5"
			]
		},
		{
			"appId": "57fb890c-0dab-4253-a5e0-7188c88b2bb4",
			"permissionIds": [
				"ecc79359-1c3b-4867-8d41-dac3aa1af9b5"
			]
		},
		{
			"appId": "d3590ed6-52b3-4102-aeff-aad2292ab01c",
			"permissionIds": [
				"ecc79359-1c3b-4867-8d41-dac3aa1af9b5"
			]
		}
	],
```

The `resourceAccess`  array should have only 4 objects. You should not have an object for `e1fe6dd8-ba31-4d61-89e7-88639da4683d`. It should look like this:

```
"resourceAccess": [
				{
					"id": "df85f4d6-205c-4ac5-a5ea-6bf408dba283",
					"type": "Scope"
				},
				{
					"id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
					"type": "Scope"
				},
				{
					"id": "37f7f235-527c-4136-accd-4a02d197296e",
					"type": "Scope"
				},
				{
					"id": "14dad69e-099b-42c9-810b-d002981feec1",
					"type": "Scope"
				}
			]
```

**Comment by hq1993922** [comment] 2019-04-22 04:04
I have redo the procedure. And I get the same error. 
![image](https://user-images.githubusercontent.com/23725260/56482345-47bfdf00-64f6-11e9-96ba-5d786951774c.png)

I guess I havenot done something extra this time.
```
web.config
    <add key="ida:ClientID" value="edf2b402-ebc3-4b27-8102-f321969043b3" />
    <add key="ida:Audience" value="edf2b402-ebc3-4b27-8102-f321969043b3" />
    <add key="ida:Password" value="P9G9qEnhhbMd8kq.eeqb0fWZTpLhs_=/" />
    <add key="ida:Issuer" value="https://login.microsoftonline.com/5ae7bf6a-a3e7-4888-9c63-4f698caef37d/v2.0" />
-------------------------------------------------------
SSOManifest
    <WebApplicationInfo>
      <Id>edf2b402-ebc3-4b27-8102-f321969043b3</Id>
      <Resource>api://localhost:44355/edf2b402-ebc3-4b27-8102-f321969043b3</Resource>
      <Scopes>
        <Scope>openid</Scope>
        <Scope>offline_access</Scope>
        <Scope>profile</Scope>
        <Scope>files.read.all</Scope>
      </Scopes>
    </WebApplicationInfo>
```

```
{
	"id": "b4ad1ac0-bc10-4e66-91bd-a36c17e2bc46",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 2,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "edf2b402-ebc3-4b27-8102-f321969043b3",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2019-04-22T03:14:32Z",
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://localhost:44355/edf2b402-ebc3-4b27-8102-f321969043b3"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "SSOAuth",
	"oauth2AllowIdTokenImplicitFlow": false,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "Enable Office to call the add-in's web APIs with the same rights as the current user.",
			"adminConsentDisplayName": "Office can act as the user.",
			"id": "e75fc299-b92e-4742-bc56-056ccaec077c",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": "Enable Office to call the add-in's web APIs with the same rights that you have.",
			"userConsentDisplayName": "Office can act as you.",
			"value": "access_as_user"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2020-04-22T03:16:25.008Z",
			"keyId": "6a2e46a5-db9c-4cad-937b-e76dee38c332",
			"startDate": "2019-04-22T03:16:28.845Z",
			"value": null,
			"createdOn": "2019-04-22T03:16:35.552422Z",
			"hint": "P9G",
			"displayName": "Password uploaded on Mon Apr 22 2019"
		}
	],
	"preAuthorizedApplications": [
		{
			"appId": "bc59ab01-8403-45c6-8796-ac3ef710b3e3",
			"permissionIds": [
				"e75fc299-b92e-4742-bc56-056ccaec077c"
			]
		},
		{
			"appId": "57fb890c-0dab-4253-a5e0-7188c88b2bb4",
			"permissionIds": [
				"e75fc299-b92e-4742-bc56-056ccaec077c"
			]
		},
		{
			"appId": "d3590ed6-52b3-4102-aeff-aad2292ab01c",
			"permissionIds": [
				"e75fc299-b92e-4742-bc56-056ccaec077c"
			]
		}
	],
	"publisherDomain": "hq1993922163.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "https://localhost:44355",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
					"type": "Scope"
				},
				{
					"id": "37f7f235-527c-4136-accd-4a02d197296e",
					"type": "Scope"
				},
				{
					"id": "14dad69e-099b-42c9-810b-d002981feec1",
					"type": "Scope"
				},
				{
					"id": "df85f4d6-205c-4ac5-a5ea-6bf408dba283",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADandPersonalMicrosoftAccount",
	"tags": [],
	"tokenEncryptionKeyId": null
}
```

**Comment by Rick-Kirkham** [comment] 2019-04-23 19:48
Did you change the values in the web.config and the manifest to match your new registration? 

If you are sure that you did, then let's go back to our earlier strategy. Please put break points in the Startup.Auth.cs and OpenIdConnectCachingSecurityTokenProvider.cs, then run the add-in again so we can see what line of code it gets to before things go wrong.

**Comment by hq1993922** [comment] 2019-04-24 09:42
I used organzitional account instead of personal account and tried those step from begining, instead of failing it worked.
Can't use personal account?

**Comment by Rick-Kirkham** [comment] 2019-04-25 00:40
SSO will work with a Work or School (that is, Office 365) account or with a Microsoft Account. It will not work with a domain or corporate account.

The user who runs the add-in has to be an account in the tenancy where the app was registered and consent was granted. In your case, that's the 5ae7bf6a-a3e7-4888-9c63-4f698caef37d tenancy.

Since you seem to be up and running again, I will close this.

**Closed as completed by Rick-Kirkham** 2019-04-25 00:40 UTC
Labels: area: authentication
